apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-grunndata-search
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: {{ min_replicas }}
    max: {{ max_replicas }}
    cpuThresholdPercentage: 50
  liveness:
    initialDelay: 20
    path: /internal/isAlive
  readiness:
    initialDelay: 20
    path: /internal/isReady
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 128Mi
  prometheus:
    enabled: true
    path: /internal/prometheus
  openSearch:
    access: read
    instance: grunndata
  env:
    - name: JAVA_OPTS
      value: "{{java_opts}}"
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: hm-grunndata-api
        - application: hm-oversikt-frontend
        - application: hm-oversikt-frontend-alpha

