apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-grunndata-search
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: {{ min_replicas }}
    max: {{ max_replicas }}
    cpuThresholdPercentage: 50
  liveness:
    initialDelay: 20
    path: /internal/isAlive
  readiness:
    initialDelay: 20
    path: /internal/isReady
  resources:
    limits:
      memory: 2548Mi
    requests:
      cpu: 200m
      memory: 128Mi
  prometheus:
    enabled: true
    path: /internal/prometheus
  openSearch:
    access: read
    instance: grunndata
  env:
    - name: JDK_JAVA_OPTS
      value: "{{java_opts}}"
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  accessPolicy:
    outbound:
      external:
        - host: navikt.github.io
    inbound:
      rules:
        - application: hm-bestillingsordning-river
        - application: hm-grunndata-api
        - application: hm-kommune-api
        - application: hm-oversikt-frontend
        - application: hm-oversikt-frontend-alpha
        - application: hm-oebs-api-proxy
        - application: hm-saksbehandling
        - application: hm-soknad
        - application: hm-soknad-api
        - application: hm-soknadsbehandling
        - application: hm-soknadsbehandling-db
        - application: hm-sortiment
        - application: hotsak-frontend
        - application: hm-forslagsmotor-tilbehoer
        - application: hm-delbestilling-api
