micronaut:
  application:
    name: hm-grunndata-search
    thread-selection: auto

jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true

opensearch:
  password: ${OPEN_SEARCH_PASSWORD:admin}
  user: ${OPEN_SEARCH_USERNAME:admin}
  url: ${OPEN_SEARCH_URI:`https://localhost:9200`}
