micronaut:
  application:
    name: hm-grunndata-search
    thread-selection: auto
  netty:
    event-loops:
      default:
        num-threads: 128
        prefer-native-transport: true
  metrics:
    enabled: true
    binders:
      uptime:
        enabled: true
      processor:
        enabled: true
      jvm:
        enabled: true
      web:
        enabled: true
      logback:
        enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
endpoints:
  metrics:
    enabled: true
  prometheus:
    sensitive: false
    enabled: true
  all:
    path: "/internal"

jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true

opensearch:
  password: ${OPEN_SEARCH_PASSWORD:admin}
  user: ${OPEN_SEARCH_USERNAME:admin}
  url: ${OPEN_SEARCH_URI:`https://localhost:9200`}
