micronaut:
  application:
    name: hm-grunndata-search
    thread-selection: auto
  netty:
    event-loops:
      default:
        num-threads: 32
        prefer-native-transport: true
  server:
    port: ${SERVER_PORT:8080}
  metrics:
    enabled: true
    binders:
      uptime:
        enabled: true
      processor:
        enabled: true
      jvm:
        enabled: true
      web:
        enabled: true
      logback:
        enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
  caches:
    digihot-sortiment-bestillingsordning:
      charset: 'UTF-8'
      expire-after-write: 1h

digihotSortiment:
  bestillingsordning: ${BESTILLINGSORDNING_URL:`https://navikt.github.io/digihot-sortiment/bestillingsordning_sortiment.json`}

endpoints:
  metrics:
    enabled: true
  prometheus:
    sensitive: false
    enabled: true
  all:
    path: "/internal"

jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true

graphql:
  enabled: true
  graphiql: # enables the /graphiql endpoint to test calls against your graph.
    enabled: ${GRAPHQL_GRAPHIQL_ENABLE:false}

opensearch:
  password: ${OPEN_SEARCH_PASSWORD:T3@mM1m3!}
  user: ${OPEN_SEARCH_USERNAME:admin}
  url: ${OPEN_SEARCH_URI:`https://localhost:9200`}

digihot:
  cluster: ${DIGIHOT_CLUSTER:`localhost`} # localhost or dev, prod
